spring:
  profiles:
    active: LOCAL
  mail:
    host: smtprelay.mhf.mhc
    port: 25
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: true  
  boot:
    admin:
      notify:
        mail:
          to: koteshwara.sastry@spglobal.com
          from: spdji-data-admin-service-dev@spglobal.com
          enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8680/eureka/}
    register-with-eureka: false
