
spring:
  application:
    name: spdji-data-admin-service
    description: This modules enables Admin services.
  mail:
    host: smtprelay.mhf.mhc
  boot:
    admin:
      notify:
        mail:
          to: koteshwara.sastry@spglobal.com, rajagopal.uppati@spglobal.com
          enabled: true
          from: spdji-data-admin-service-dev@spglobal.com
      routes:
        endpoints: env, metrics, trace, jolokia, info, configprops 
  security:
    user: 
      name: admin
      password: admin
