spring:
  profiles:
    active: LOCAL
  mail:
    host: 
    port: 25
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: true  
  boot:
    admin:
      notify:
        mail:
          to: 
          from: 
          enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8680/eureka/}
    register-with-eureka: false
